baseURL = "https://stilllearning.tech/"
title = "Still Learning"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Still Learning"
description = "A personal blog about learning and how I break things."
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Vibhakar 'Gala' Solanki"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "My name is **Vibhakar \"gala\" Solanki**, and I'm a software engineer. I'm in my final year of B.Tech degree.  \n  \nI'm passionate about building scalable, reliable, and performant systems.  \nInterested in Machine Learning, distributed systems, and web dev. and currently learning about [Rust](https://www.rust-lang.org) and maintaining [Battlefield Portal Community](github.com/battlefield-portal-community/).  \nI am also doing **freelacing** work."

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/gala_vs"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/p0lygun"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/p0lygun/p0lygun.github.io/tree/main/content/blog"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "diary"
name = "Diary"
url = "/diary/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2



# [[menu.main]]
# identifier = "categories"
# name = "Categories"
# url = "/categories/"
# weight = 10

# [[menu.main]]
# identifier = "tags"
# name = "Tags"
# url = "/tags/"
# weight = 20



[markup.highlight]
noClasses = false

[[module.mounts]]
source = 'images'
target = 'static/img'
